#!/bin/bash
# Install nexus-runner as a macOS LaunchAgent.
#
# macOS Sequoia/Tahoe blocks launchd-spawned processes from reading ~/Documents/
# (TCC restriction). This script works around that by:
#   1. Bundling the runner with esbuild into a single self-contained .mjs file
#   2. Copying the bundle + config + start wrapper to ~/.nexus/runner/  (NOT in ~/Documents)
#   3. Pointing the LaunchAgent at the deployed copy
#
# Source files stay in ~/Documents/assistant/nexus-runner/ for editing.
# After every code change: re-run this script (it rebuilds + redeploys).

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
LABEL="com.eli.nexus-runner"
PLIST="$HOME/Library/LaunchAgents/${LABEL}.plist"
LOG_DIR="$HOME/Library/Logs"
DEPLOY_DIR="$HOME/.nexus/runner"

mkdir -p "$LOG_DIR" "$HOME/Library/LaunchAgents" "$DEPLOY_DIR"

cd "$DIR"

# ---------------------------------------------------------------------------
# 1. Build TypeScript and bundle into a single self-contained .mjs file
# ---------------------------------------------------------------------------
echo "[install] tsc..."
npx tsc --noEmitOnError false 2>&1 || true

echo "[install] bundling with esbuild..."
# CJS deps like `ws` use top-level `require()`. In ESM bundles, `require` doesn't
# exist natively — we provide it via createRequire in a banner so CJS interop works.
npx esbuild src/runner.ts \
    --bundle \
    --platform=node \
    --target=node20 \
    --format=esm \
    --outfile="$DEPLOY_DIR/runner.mjs" \
    --banner:js="import { createRequire as _createRequire } from 'module';const require = _createRequire(import.meta.url);" \
    --log-level=warning

echo "[install] copying config..."
cp config.json "$DEPLOY_DIR/config.json"

# ---------------------------------------------------------------------------
# 2. Generate the deployed start.sh wrapper
# ---------------------------------------------------------------------------
cat > "$DEPLOY_DIR/start.sh" <<'SHELL_EOF'
#!/bin/bash
# Auto-generated by install-launchd.sh — do not edit.
# Sources secrets and execs node on the bundled runner.

set -e
DIR="$(cd "$(dirname "$0")" && pwd)"

SECRETS="$HOME/.nexus/secrets.env"
if [ ! -f "$SECRETS" ]; then
    echo "[error] $SECRETS not found"
    exit 1
fi
set -a
# shellcheck disable=SC1090
source "$SECRETS"
set +a

export TZ="${TZ:-Asia/Jerusalem}"
export NEXUS_RUNNER_CONFIG="$DIR/config.json"
export NEXUS_RUNNER_LOG="${NEXUS_RUNNER_LOG:-$HOME/Library/Logs/nexus-runner.log}"

# Find node — launchd has a minimal PATH
NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
    for candidate in \
        /opt/homebrew/bin/node \
        /usr/local/bin/node \
        "$HOME/.nvm/versions/node/$(ls "$HOME/.nvm/versions/node" 2>/dev/null | tail -1)/bin/node" \
        ; do
        if [ -x "$candidate" ]; then
            NODE_BIN="$candidate"
            break
        fi
    done
fi
if [ -z "$NODE_BIN" ]; then
    echo "[error] node not found"
    exit 1
fi

echo "[start] $(date) — node=$NODE_BIN tz=$TZ"
exec "$NODE_BIN" "$DIR/runner.mjs"
SHELL_EOF
chmod +x "$DEPLOY_DIR/start.sh"

echo "[install] deployed to $DEPLOY_DIR/"
ls -la "$DEPLOY_DIR" | sed 's/^/    /'

# ---------------------------------------------------------------------------
# 3. Generate the LaunchAgent plist (points at the deployed copy)
# ---------------------------------------------------------------------------
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${DEPLOY_DIR}/start.sh</string>
    </array>

    <key>WorkingDirectory</key>
    <string>${DEPLOY_DIR}</string>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>

    <key>ThrottleInterval</key>
    <integer>10</integer>

    <key>StandardOutPath</key>
    <string>${LOG_DIR}/nexus-runner.out.log</string>

    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/nexus-runner.err.log</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
</dict>
</plist>
EOF

echo "[install] wrote $PLIST"

# ---------------------------------------------------------------------------
# 4. (Re)load the agent
# ---------------------------------------------------------------------------
if launchctl list | grep -q "$LABEL"; then
    echo "[install] reloading existing agent..."
    launchctl unload "$PLIST" 2>/dev/null || true
fi
launchctl load "$PLIST"
echo "[install] loaded $LABEL"

echo
echo "Logs:"
echo "  $LOG_DIR/nexus-runner.out.log    (launchd stdout — start.sh output)"
echo "  $LOG_DIR/nexus-runner.err.log    (launchd stderr — errors)"
echo "  $HOME/Library/Logs/nexus-runner.log  (runner's own structured log)"
echo
echo "Manage:"
echo "  launchctl list | grep $LABEL"
echo "  launchctl unload $PLIST    # stop"
echo "  launchctl load $PLIST      # start"
echo "  ./uninstall-launchd.sh     # remove"
echo
echo "Re-run this script after every code change to redeploy."
